export const opcionesConstants = {
    OBTENER_OPCIONES: 'OBTENER_OPCIONES',
    CARGAR_CREATE_OPCION: 'CARGAR_CREATE_OPCION',
    CARGAR_EDITAR_OPCION: 'CARGAR_EDITAR_OPCION',
    MOSTRAR_CREATE_OPCION: 'MOSTRAR_CREATE_OPCION',
    MOSTRAR_EDITAR_OPCION: 'MOSTRAR_EDITAR_OPCION',
    CREAR_OPCION: 'CREAR_OPCION',
    EDITAR_OPCION: 'EDITAR_OPCION',
    OPCION_SELECCIONADA: 'OPCION_SELECCIONADA'
};