export const cardConstants = {
    OBTENER_CARDS: 'OBTENER_CARDS',
    CARGAR_CREATE_CARD: 'CARGAR_CREATE_CARD',
    CARGAR_EDITAR_CARD: 'CARGAR_EDITAR_CARD',
    MOSTRAR_CREATE_CARD: 'MOSTRAR_CREATE_CARD',
    MOSTRAR_EDITAR_CARD: 'MOSTRAR_EDITAR_CARD',
    CREAR_CARD: 'CREAR_CARD',
    EDITAR_CARD: 'EDITAR_CARD',
    ELIMINAR_CARD: 'ELIMINAR_CARD',
    CARD_SELECCIONADA: 'CARD_SELECCIONADA'
};