export const categoriaConstants = {
    OBTENER_CATEGORIAS: 'OBTENER_CATEGORIAS',
    CARGAR_CREATE_CATEGORIA: 'CARGAR_CREATE_CATEGORIA',
    CARGAR_EDITAR_CATEGORIA: 'CARGAR_EDITAR_CATEGORIA',
    MOSTRAR_CREATE_CATEGORIA: 'MOSTRAR_CREATE_CATEGORIA',
    MOSTRAR_EDITAR_CATEGORIA: 'MOSTRAR_EDITAR_CATEGORIA',
    CREAR_CATEGORIA: 'CREAR_CATEGORIA',
    EDITAR_CATEGORIA: 'EDITAR_CATEGORIA',
    CATEGORIA_SELECCIONADA: 'CATEGORIA_SELECCIONADA'
};