export const bannerConstants = {
    OBTENER_BANNERS: 'OBTENER_BANNERS',
    CARGAR_CREATE_BANNER: 'CARGAR_CREATE_BANNER',
    CARGAR_EDITAR_BANNER: 'CARGAR_EDITAR_BANNER',
    MOSTRAR_CREATE_BANNER: 'MOSTRAR_CREATE_BANNER',
    MOSTRAR_EDITAR_BANNER: 'MOSTRAR_EDITAR_BANNER',
    CREAR_BANNER: 'CREAR_BANNER',
    EDITAR_BANNER: 'EDITAR_BANNER',
    BANNER_SELECCIONADO: 'CATEGORIA_SELECCIONADO'
};