export const horarioConstants = {
    OBTENER_HORARIOS: 'OBTENER_HORARIOS',
    CARGAR_CREATE_HORARIO: 'CARGAR_CREATE_HORARIO',
    CARGAR_EDITAR_HORARIO: 'CARGAR_EDITAR_HORARIO',
    MOSTRAR_CREATE_HORARIO: 'MOSTRAR_CREATE_HORARIO',
    MOSTRAR_EDITAR_HORARIO: 'MOSTRAR_EDITAR_HORARIO',
    CREAR_HORARIO: 'CREAR_HORARIO',
    EDITAR_HORARIO: 'EDITAR_HORARIO',
    ELIMINAR_HORARIO: 'ELIMINAR_HORARIO',
    HORARIO_SELECCIONADO: 'HORARIO_SELECCIONADO',
    HORARIO_RANGO:'HORARIO_RANGO'
  };