export const  pedidosConstants = {
    OBTENER_PEDIDOS: 'OBTENER_PEDIDOS',
    MOSTRAR_DETALLE_PEDIDO: 'MOSTRAR_DETALLE_PEDIDO',
    OBTENER_PEDIDO: 'OBTENER_PEDIDO',
    SELECCIONAR_PEDIDO: 'SELECCIONAR_PEDIDO',
    CAMBIAR_ESTADO: 'CAMBIAR_ESTADO',
    ENVIAR_PEDIDO: 'ENVIAR_PEDIDO',
}