export const productoConstants = {
    OBTENER_PRODUCTOS: 'OBTENER_PRODUCTOS',
    OBTENER_OPCIONES_PRODUCTO: 'OBTENER_OPCIONES_PRODUCTO',
    CARGAR_CREATE_PRODUCTO: 'CARGAR_CREATE_PRODUCTO',
    CARGAR_EDITAR_PRODUCTO: 'CARGAR_EDITAR_PRODUCTO',
    MOSTRAR_CREATE_PRODUCTO: 'MOSTRAR_CREATE_PRODUCTO',
    MOSTRAR_EDITAR_PRODUCTO: 'MOSTRAR_EDITAR_PRODUCTO',
    CREAR_PRODUCTO: 'CREAR_PRODUCTO',
    EDITAR_PRODUCTO: 'EDITAR_PRODUCTO',
    PRODUCTO_SELECCIONADO: 'PRODUCTO_SELECCIONADO',
    OPCION_PRODUCTO_SELECCIONADA: 'OPCION_PRODUCTO_SELECCIONADA',
};