export const productoConstants = {
    OBTENER_PRODUCTOS: 'OBTENER_PRODUCTOS',
    OBTENER_OPCIONES_PRODUCTO: 'OBTENER_OPCIONES_PRODUCTO',
    OBTENER_OPCIONES_SELECCION: 'OBTENER_OPCIONES_SELECCION',
    CARGAR_CREATE_PRODUCTO: 'CARGAR_CREATE_PRODUCTO',
    CARGAR_EDITAR_PRODUCTO: 'CARGAR_EDITAR_PRODUCTO',
    MOSTRAR_CREATE_PRODUCTO: 'MOSTRAR_CREATE_PRODUCTO',
    MOSTRAR_EDITAR_PRODUCTO: 'MOSTRAR_EDITAR_PRODUCTO',
    MOSTRAR_SELECCION_OPCION: 'MOSTRAR_SELECCION_OPCION',
    CREAR_PRODUCTO: 'CREAR_PRODUCTO',
    EDITAR_PRODUCTO: 'EDITAR_PRODUCTO',
    PRODUCTO_SELECCIONADO: 'PRODUCTO_SELECCIONADO',
    OPCION_PRODUCTO_SELECCIONADA: 'OPCION_PRODUCTO_SELECCIONADA',
    CREAR_OPCIONES_PRODUCTO: 'CREAR_OPCIONES_PRODUCTO',
    ELIMINAR_OPCION_PRODUCTO: 'ELIMINAR_OPCION_PRODUCTO',
    PRODUCTOS_POR_CATEGORIA:'PRODUCTOS_POR_CATEGORIA',

    
    
};